" vim(1)

set nocompatible

set autoindent
set backspace=indent
set directory=~/.vim/swap//
set encoding=utf-8
set expandtab
set incsearch
set listchars=space:\\u00b7,tab:\ \ \\u2192
set report=0
set ruler
set shiftwidth=4
set softtabstop=4
set splitbelow
set splitright
set viminfofile=~/.vim/info

filetype plugin indent on
syntax on

augroup highlight
    autocmd!
    autocmd CmdlineEnter /,\? set hlsearch
    autocmd CmdlineLeave /,\? set nohlsearch
    autocmd FileType * match Todo /\s\+$/
    autocmd InsertEnter * match none
    autocmd InsertLeave * match Todo /\s\+$/
augroup end
